# Base image
FROM node:24.11.1-alpine

WORKDIR /app

# Accept a build-time argument
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Prisma needs openssl
RUN apk add --no-cache openssl

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Generate Prisma Client
# Prisma generate doesn't need actual DATABASE_URL connection
RUN npx prisma generate

# 👉 Run build ONLY in production
RUN if [ "$NODE_ENV" = "production" ] ; then npm run build ; fi

EXPOSE 3000

# Start dev mode by default
CMD ["npm", "run", "dev"]
